version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/azure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ovh"
    schedule:
      interval: "weekly"
