name: Deploy Terraform AWS

on:
  workflow_dispatch:
    inputs:
      ghes_version:
        description: 'GitHub Enterprise Server version'
        required: true
        default: '3.11.2'
      aws_instance_type:
        description: 'AWS instance type'
        required: true
        default: 'm5.8xlarge'

env:
  domain: dupoiron.com
  subdomain: ghes

jobs:
  terraform:
    runs-on: ubuntu-latest
  
    env:
      TF_VAR_ghes_version: ${{ github.event.inputs.ghes_version }}
      TF_VAR_aws_instance_type: ${{ github.event.inputs.aws_instance_type }} 

    outputs:
      public_ip: ${{ steps.deploy.outputs.public_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        id: deploy
        working-directory: aws
        run: | 
          terraform init -backend-config=backend.conf
          terraform plan -var "ghes_version=${{ env.TF_VAR_ghes_version }}" -var "aws_instance_type=${{ env.TF_VAR_aws_instance_type }}" -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > terraform_output.json
          echo "public_ip=$(cat terraform_output.json | jq -r '.ghes_ec2_public_ip.value')" >> "$GITHUB_OUTPUT"
        env:
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  summary:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Summary
        run: |
          echo "GHES version: ${{ github.event.inputs.ghes_version }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Public IP: ${{ needs.terraform.outputs.public_ip }}" >> "$GITHUB_STEP_SUMMARY"
          echo "SSH access: ssh admin@${{ needs.terraform.outputs.public_ip }} -p122" >> "$GITHUB_STEP_SUMMARY"
          echo "Home page: https://${{ env.subdomain }}.${{ env.domain }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Management console: https://${{ needs.terraform.outputs.public_ip }}:8443/setup" >> "$GITHUB_STEP_SUMMARY"
